import Head from 'next/head'

import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className='lazy col-md-12 align-items-center mt-5'>
        <h1 className='d-flex justify-content-center align-items-center'>Find latest news of bangladesh and around the world</h1>
        <div>
          <h2 className='d-flex justify-content-center align-items-center'>Too lazy to read the whole news?</h2>
          <div>
            <h2 className='d-flex justify-content-center '>Summarize the article or news in seconds!</h2>
          </div>
        </div>
      </div>
      
      
    </div>
  )
}
